//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IMS.wrSettings {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wrSettingsSoap", Namespace="http://tempuri.org/")]
    public partial class wrSettings : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetInvoiceNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetQuickInvoiceNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceInvoiceNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wrSettings() {
            this.Url = global::IMS.Properties.Settings.Default.IMS_wrSettings_wrSettings;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetInvoiceNoCompletedEventHandler GetInvoiceNoCompleted;
        
        /// <remarks/>
        public event GetQuickInvoiceNoCompletedEventHandler GetQuickInvoiceNoCompleted;
        
        /// <remarks/>
        public event GetServiceInvoiceNoCompletedEventHandler GetServiceInvoiceNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoiceNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetInvoiceNo(System.DateTime dt, string Table, string ShortName) {
            object[] results = this.Invoke("GetInvoiceNo", new object[] {
                        dt,
                        Table,
                        ShortName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceNoAsync(System.DateTime dt, string Table, string ShortName) {
            this.GetInvoiceNoAsync(dt, Table, ShortName, null);
        }
        
        /// <remarks/>
        public void GetInvoiceNoAsync(System.DateTime dt, string Table, string ShortName, object userState) {
            if ((this.GetInvoiceNoOperationCompleted == null)) {
                this.GetInvoiceNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceNoOperationCompleted);
            }
            this.InvokeAsync("GetInvoiceNo", new object[] {
                        dt,
                        Table,
                        ShortName}, this.GetInvoiceNoOperationCompleted, userState);
        }
        
        private void OnGetInvoiceNoOperationCompleted(object arg) {
            if ((this.GetInvoiceNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceNoCompleted(this, new GetInvoiceNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetQuickInvoiceNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetQuickInvoiceNo(System.DateTime dt, string ShortName) {
            object[] results = this.Invoke("GetQuickInvoiceNo", new object[] {
                        dt,
                        ShortName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetQuickInvoiceNoAsync(System.DateTime dt, string ShortName) {
            this.GetQuickInvoiceNoAsync(dt, ShortName, null);
        }
        
        /// <remarks/>
        public void GetQuickInvoiceNoAsync(System.DateTime dt, string ShortName, object userState) {
            if ((this.GetQuickInvoiceNoOperationCompleted == null)) {
                this.GetQuickInvoiceNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQuickInvoiceNoOperationCompleted);
            }
            this.InvokeAsync("GetQuickInvoiceNo", new object[] {
                        dt,
                        ShortName}, this.GetQuickInvoiceNoOperationCompleted, userState);
        }
        
        private void OnGetQuickInvoiceNoOperationCompleted(object arg) {
            if ((this.GetQuickInvoiceNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQuickInvoiceNoCompleted(this, new GetQuickInvoiceNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetServiceInvoiceNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetServiceInvoiceNo(System.DateTime dt, string ShortName) {
            object[] results = this.Invoke("GetServiceInvoiceNo", new object[] {
                        dt,
                        ShortName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceInvoiceNoAsync(System.DateTime dt, string ShortName) {
            this.GetServiceInvoiceNoAsync(dt, ShortName, null);
        }
        
        /// <remarks/>
        public void GetServiceInvoiceNoAsync(System.DateTime dt, string ShortName, object userState) {
            if ((this.GetServiceInvoiceNoOperationCompleted == null)) {
                this.GetServiceInvoiceNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceInvoiceNoOperationCompleted);
            }
            this.InvokeAsync("GetServiceInvoiceNo", new object[] {
                        dt,
                        ShortName}, this.GetServiceInvoiceNoOperationCompleted, userState);
        }
        
        private void OnGetServiceInvoiceNoOperationCompleted(object arg) {
            if ((this.GetServiceInvoiceNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceInvoiceNoCompleted(this, new GetServiceInvoiceNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetInvoiceNoCompletedEventHandler(object sender, GetInvoiceNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetQuickInvoiceNoCompletedEventHandler(object sender, GetQuickInvoiceNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQuickInvoiceNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetQuickInvoiceNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetServiceInvoiceNoCompletedEventHandler(object sender, GetServiceInvoiceNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceInvoiceNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceInvoiceNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591