//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IMS.wrSales {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsSalesSoap", Namespace="http://tempuri.org/")]
    public partial class wsSales : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddSaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddSaleDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSalesByInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteSalesByInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerByInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSoldProductsByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSoldProductsByDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSoldProductsByInvoiceNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProfitLossByDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getProfitLossByDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalesToCustomerByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalesToCustomerByDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSaleDetailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsSales() {
            this.Url = global::IMS.Properties.Settings.Default.IMS_wrSales_wsSales;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddSaleCompletedEventHandler AddSaleCompleted;
        
        /// <remarks/>
        public event AddSaleDetailsCompletedEventHandler AddSaleDetailsCompleted;
        
        /// <remarks/>
        public event GetSalesCompletedEventHandler GetSalesCompleted;
        
        /// <remarks/>
        public event getSalesByInvoiceCompletedEventHandler getSalesByInvoiceCompleted;
        
        /// <remarks/>
        public event DeleteSalesByInvoiceCompletedEventHandler DeleteSalesByInvoiceCompleted;
        
        /// <remarks/>
        public event GetCustomerByInvoiceCompletedEventHandler GetCustomerByInvoiceCompleted;
        
        /// <remarks/>
        public event getSoldProductsByDateCompletedEventHandler getSoldProductsByDateCompleted;
        
        /// <remarks/>
        public event getSoldProductsByDatesCompletedEventHandler getSoldProductsByDatesCompleted;
        
        /// <remarks/>
        public event getSoldProductsByInvoiceNoCompletedEventHandler getSoldProductsByInvoiceNoCompleted;
        
        /// <remarks/>
        public event getProfitLossByDateCompletedEventHandler getProfitLossByDateCompleted;
        
        /// <remarks/>
        public event getProfitLossByDatesCompletedEventHandler getProfitLossByDatesCompleted;
        
        /// <remarks/>
        public event SalesToCustomerByIDCompletedEventHandler SalesToCustomerByIDCompleted;
        
        /// <remarks/>
        public event SalesToCustomerByDatesCompletedEventHandler SalesToCustomerByDatesCompleted;
        
        /// <remarks/>
        public event UpdateSalesCompletedEventHandler UpdateSalesCompleted;
        
        /// <remarks/>
        public event UpdateSaleDetailCompletedEventHandler UpdateSaleDetailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddSale", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client AddSale(Sale sls) {
            object[] results = this.Invoke("AddSale", new object[] {
                        sls});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void AddSaleAsync(Sale sls) {
            this.AddSaleAsync(sls, null);
        }
        
        /// <remarks/>
        public void AddSaleAsync(Sale sls, object userState) {
            if ((this.AddSaleOperationCompleted == null)) {
                this.AddSaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSaleOperationCompleted);
            }
            this.InvokeAsync("AddSale", new object[] {
                        sls}, this.AddSaleOperationCompleted, userState);
        }
        
        private void OnAddSaleOperationCompleted(object arg) {
            if ((this.AddSaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSaleCompleted(this, new AddSaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddSaleDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client AddSaleDetails(SaleDetail s) {
            object[] results = this.Invoke("AddSaleDetails", new object[] {
                        s});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void AddSaleDetailsAsync(SaleDetail s) {
            this.AddSaleDetailsAsync(s, null);
        }
        
        /// <remarks/>
        public void AddSaleDetailsAsync(SaleDetail s, object userState) {
            if ((this.AddSaleDetailsOperationCompleted == null)) {
                this.AddSaleDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddSaleDetailsOperationCompleted);
            }
            this.InvokeAsync("AddSaleDetails", new object[] {
                        s}, this.AddSaleDetailsOperationCompleted, userState);
        }
        
        private void OnAddSaleDetailsOperationCompleted(object arg) {
            if ((this.AddSaleDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddSaleDetailsCompleted(this, new AddSaleDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client GetSales() {
            object[] results = this.Invoke("GetSales", new object[0]);
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesAsync() {
            this.GetSalesAsync(null);
        }
        
        /// <remarks/>
        public void GetSalesAsync(object userState) {
            if ((this.GetSalesOperationCompleted == null)) {
                this.GetSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesOperationCompleted);
            }
            this.InvokeAsync("GetSales", new object[0], this.GetSalesOperationCompleted, userState);
        }
        
        private void OnGetSalesOperationCompleted(object arg) {
            if ((this.GetSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesCompleted(this, new GetSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSalesByInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client getSalesByInvoice(string InvoiceNo) {
            object[] results = this.Invoke("getSalesByInvoice", new object[] {
                        InvoiceNo});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void getSalesByInvoiceAsync(string InvoiceNo) {
            this.getSalesByInvoiceAsync(InvoiceNo, null);
        }
        
        /// <remarks/>
        public void getSalesByInvoiceAsync(string InvoiceNo, object userState) {
            if ((this.getSalesByInvoiceOperationCompleted == null)) {
                this.getSalesByInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSalesByInvoiceOperationCompleted);
            }
            this.InvokeAsync("getSalesByInvoice", new object[] {
                        InvoiceNo}, this.getSalesByInvoiceOperationCompleted, userState);
        }
        
        private void OngetSalesByInvoiceOperationCompleted(object arg) {
            if ((this.getSalesByInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSalesByInvoiceCompleted(this, new getSalesByInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteSalesByInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client DeleteSalesByInvoice(string InvoiceNo) {
            object[] results = this.Invoke("DeleteSalesByInvoice", new object[] {
                        InvoiceNo});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteSalesByInvoiceAsync(string InvoiceNo) {
            this.DeleteSalesByInvoiceAsync(InvoiceNo, null);
        }
        
        /// <remarks/>
        public void DeleteSalesByInvoiceAsync(string InvoiceNo, object userState) {
            if ((this.DeleteSalesByInvoiceOperationCompleted == null)) {
                this.DeleteSalesByInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteSalesByInvoiceOperationCompleted);
            }
            this.InvokeAsync("DeleteSalesByInvoice", new object[] {
                        InvoiceNo}, this.DeleteSalesByInvoiceOperationCompleted, userState);
        }
        
        private void OnDeleteSalesByInvoiceOperationCompleted(object arg) {
            if ((this.DeleteSalesByInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteSalesByInvoiceCompleted(this, new DeleteSalesByInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerByInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Customer GetCustomerByInvoice(string InvoiceNo) {
            object[] results = this.Invoke("GetCustomerByInvoice", new object[] {
                        InvoiceNo});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerByInvoiceAsync(string InvoiceNo) {
            this.GetCustomerByInvoiceAsync(InvoiceNo, null);
        }
        
        /// <remarks/>
        public void GetCustomerByInvoiceAsync(string InvoiceNo, object userState) {
            if ((this.GetCustomerByInvoiceOperationCompleted == null)) {
                this.GetCustomerByInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerByInvoiceOperationCompleted);
            }
            this.InvokeAsync("GetCustomerByInvoice", new object[] {
                        InvoiceNo}, this.GetCustomerByInvoiceOperationCompleted, userState);
        }
        
        private void OnGetCustomerByInvoiceOperationCompleted(object arg) {
            if ((this.GetCustomerByInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerByInvoiceCompleted(this, new GetCustomerByInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSoldProductsByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client getSoldProductsByDate(System.DateTime dt) {
            object[] results = this.Invoke("getSoldProductsByDate", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void getSoldProductsByDateAsync(System.DateTime dt) {
            this.getSoldProductsByDateAsync(dt, null);
        }
        
        /// <remarks/>
        public void getSoldProductsByDateAsync(System.DateTime dt, object userState) {
            if ((this.getSoldProductsByDateOperationCompleted == null)) {
                this.getSoldProductsByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSoldProductsByDateOperationCompleted);
            }
            this.InvokeAsync("getSoldProductsByDate", new object[] {
                        dt}, this.getSoldProductsByDateOperationCompleted, userState);
        }
        
        private void OngetSoldProductsByDateOperationCompleted(object arg) {
            if ((this.getSoldProductsByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSoldProductsByDateCompleted(this, new getSoldProductsByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSoldProductsByDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client getSoldProductsByDates(System.DateTime dtFR, System.DateTime dtTO) {
            object[] results = this.Invoke("getSoldProductsByDates", new object[] {
                        dtFR,
                        dtTO});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void getSoldProductsByDatesAsync(System.DateTime dtFR, System.DateTime dtTO) {
            this.getSoldProductsByDatesAsync(dtFR, dtTO, null);
        }
        
        /// <remarks/>
        public void getSoldProductsByDatesAsync(System.DateTime dtFR, System.DateTime dtTO, object userState) {
            if ((this.getSoldProductsByDatesOperationCompleted == null)) {
                this.getSoldProductsByDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSoldProductsByDatesOperationCompleted);
            }
            this.InvokeAsync("getSoldProductsByDates", new object[] {
                        dtFR,
                        dtTO}, this.getSoldProductsByDatesOperationCompleted, userState);
        }
        
        private void OngetSoldProductsByDatesOperationCompleted(object arg) {
            if ((this.getSoldProductsByDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSoldProductsByDatesCompleted(this, new getSoldProductsByDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSoldProductsByInvoiceNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client getSoldProductsByInvoiceNo(string InvoiceNo) {
            object[] results = this.Invoke("getSoldProductsByInvoiceNo", new object[] {
                        InvoiceNo});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void getSoldProductsByInvoiceNoAsync(string InvoiceNo) {
            this.getSoldProductsByInvoiceNoAsync(InvoiceNo, null);
        }
        
        /// <remarks/>
        public void getSoldProductsByInvoiceNoAsync(string InvoiceNo, object userState) {
            if ((this.getSoldProductsByInvoiceNoOperationCompleted == null)) {
                this.getSoldProductsByInvoiceNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSoldProductsByInvoiceNoOperationCompleted);
            }
            this.InvokeAsync("getSoldProductsByInvoiceNo", new object[] {
                        InvoiceNo}, this.getSoldProductsByInvoiceNoOperationCompleted, userState);
        }
        
        private void OngetSoldProductsByInvoiceNoOperationCompleted(object arg) {
            if ((this.getSoldProductsByInvoiceNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSoldProductsByInvoiceNoCompleted(this, new getSoldProductsByInvoiceNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getProfitLossByDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client getProfitLossByDate(System.DateTime dt) {
            object[] results = this.Invoke("getProfitLossByDate", new object[] {
                        dt});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void getProfitLossByDateAsync(System.DateTime dt) {
            this.getProfitLossByDateAsync(dt, null);
        }
        
        /// <remarks/>
        public void getProfitLossByDateAsync(System.DateTime dt, object userState) {
            if ((this.getProfitLossByDateOperationCompleted == null)) {
                this.getProfitLossByDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProfitLossByDateOperationCompleted);
            }
            this.InvokeAsync("getProfitLossByDate", new object[] {
                        dt}, this.getProfitLossByDateOperationCompleted, userState);
        }
        
        private void OngetProfitLossByDateOperationCompleted(object arg) {
            if ((this.getProfitLossByDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProfitLossByDateCompleted(this, new getProfitLossByDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getProfitLossByDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client getProfitLossByDates(System.DateTime dtFR, System.DateTime dtTO) {
            object[] results = this.Invoke("getProfitLossByDates", new object[] {
                        dtFR,
                        dtTO});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void getProfitLossByDatesAsync(System.DateTime dtFR, System.DateTime dtTO) {
            this.getProfitLossByDatesAsync(dtFR, dtTO, null);
        }
        
        /// <remarks/>
        public void getProfitLossByDatesAsync(System.DateTime dtFR, System.DateTime dtTO, object userState) {
            if ((this.getProfitLossByDatesOperationCompleted == null)) {
                this.getProfitLossByDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetProfitLossByDatesOperationCompleted);
            }
            this.InvokeAsync("getProfitLossByDates", new object[] {
                        dtFR,
                        dtTO}, this.getProfitLossByDatesOperationCompleted, userState);
        }
        
        private void OngetProfitLossByDatesOperationCompleted(object arg) {
            if ((this.getProfitLossByDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getProfitLossByDatesCompleted(this, new getProfitLossByDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SalesToCustomerByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client SalesToCustomerByID(int CustomerID) {
            object[] results = this.Invoke("SalesToCustomerByID", new object[] {
                        CustomerID});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void SalesToCustomerByIDAsync(int CustomerID) {
            this.SalesToCustomerByIDAsync(CustomerID, null);
        }
        
        /// <remarks/>
        public void SalesToCustomerByIDAsync(int CustomerID, object userState) {
            if ((this.SalesToCustomerByIDOperationCompleted == null)) {
                this.SalesToCustomerByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalesToCustomerByIDOperationCompleted);
            }
            this.InvokeAsync("SalesToCustomerByID", new object[] {
                        CustomerID}, this.SalesToCustomerByIDOperationCompleted, userState);
        }
        
        private void OnSalesToCustomerByIDOperationCompleted(object arg) {
            if ((this.SalesToCustomerByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalesToCustomerByIDCompleted(this, new SalesToCustomerByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SalesToCustomerByDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client SalesToCustomerByDates(int CID, System.DateTime dtF, System.DateTime dtT) {
            object[] results = this.Invoke("SalesToCustomerByDates", new object[] {
                        CID,
                        dtF,
                        dtT});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void SalesToCustomerByDatesAsync(int CID, System.DateTime dtF, System.DateTime dtT) {
            this.SalesToCustomerByDatesAsync(CID, dtF, dtT, null);
        }
        
        /// <remarks/>
        public void SalesToCustomerByDatesAsync(int CID, System.DateTime dtF, System.DateTime dtT, object userState) {
            if ((this.SalesToCustomerByDatesOperationCompleted == null)) {
                this.SalesToCustomerByDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalesToCustomerByDatesOperationCompleted);
            }
            this.InvokeAsync("SalesToCustomerByDates", new object[] {
                        CID,
                        dtF,
                        dtT}, this.SalesToCustomerByDatesOperationCompleted, userState);
        }
        
        private void OnSalesToCustomerByDatesOperationCompleted(object arg) {
            if ((this.SalesToCustomerByDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalesToCustomerByDatesCompleted(this, new SalesToCustomerByDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client UpdateSales(Sale s) {
            object[] results = this.Invoke("UpdateSales", new object[] {
                        s});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSalesAsync(Sale s) {
            this.UpdateSalesAsync(s, null);
        }
        
        /// <remarks/>
        public void UpdateSalesAsync(Sale s, object userState) {
            if ((this.UpdateSalesOperationCompleted == null)) {
                this.UpdateSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSalesOperationCompleted);
            }
            this.InvokeAsync("UpdateSales", new object[] {
                        s}, this.UpdateSalesOperationCompleted, userState);
        }
        
        private void OnUpdateSalesOperationCompleted(object arg) {
            if ((this.UpdateSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSalesCompleted(this, new UpdateSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateSaleDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Server2Client UpdateSaleDetail(SaleDetail sd) {
            object[] results = this.Invoke("UpdateSaleDetail", new object[] {
                        sd});
            return ((Server2Client)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSaleDetailAsync(SaleDetail sd) {
            this.UpdateSaleDetailAsync(sd, null);
        }
        
        /// <remarks/>
        public void UpdateSaleDetailAsync(SaleDetail sd, object userState) {
            if ((this.UpdateSaleDetailOperationCompleted == null)) {
                this.UpdateSaleDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSaleDetailOperationCompleted);
            }
            this.InvokeAsync("UpdateSaleDetail", new object[] {
                        sd}, this.UpdateSaleDetailOperationCompleted, userState);
        }
        
        private void OnUpdateSaleDetailOperationCompleted(object arg) {
            if ((this.UpdateSaleDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSaleDetailCompleted(this, new UpdateSaleDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sale {
        
        private int saleIDField;
        
        private string invoiceNoField;
        
        private System.DateTime saleDateField;
        
        private int customerIDField;
        
        private double amountField;
        
        private double discountField;
        
        private double paymentField;
        
        private double balanceField;
        
        /// <remarks/>
        public int SaleID {
            get {
                return this.saleIDField;
            }
            set {
                this.saleIDField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SaleDate {
            get {
                return this.saleDateField;
            }
            set {
                this.saleDateField = value;
            }
        }
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public double Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        public double Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        public double Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Customer {
        
        private int customerIDField;
        
        private string customerNameField;
        
        private string addressField;
        
        private string phoneField;
        
        private string emailField;
        
        private string balanceField;
        
        /// <remarks/>
        public int CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleDetail {
        
        private int saleDetailIDField;
        
        private string invoiceNoField;
        
        private int productIDField;
        
        private double buyingValueField;
        
        private double sellingValueField;
        
        private int quantityField;
        
        private double amountField;
        
        /// <remarks/>
        public int SaleDetailID {
            get {
                return this.saleDetailIDField;
            }
            set {
                this.saleDetailIDField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public int ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public double BuyingValue {
            get {
                return this.buyingValueField;
            }
            set {
                this.buyingValueField = value;
            }
        }
        
        /// <remarks/>
        public double SellingValue {
            get {
                return this.sellingValueField;
            }
            set {
                this.sellingValueField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Server2Client {
        
        private int countField;
        
        private double valueField;
        
        private string messageField;
        
        private System.Data.DataTable dataTableField;
        
        private System.Data.DataSet dataSetField;
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable dataTable {
            get {
                return this.dataTableField;
            }
            set {
                this.dataTableField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dataSet {
            get {
                return this.dataSetField;
            }
            set {
                this.dataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddSaleCompletedEventHandler(object sender, AddSaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void AddSaleDetailsCompletedEventHandler(object sender, AddSaleDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddSaleDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddSaleDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetSalesCompletedEventHandler(object sender, GetSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getSalesByInvoiceCompletedEventHandler(object sender, getSalesByInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSalesByInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSalesByInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void DeleteSalesByInvoiceCompletedEventHandler(object sender, DeleteSalesByInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteSalesByInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteSalesByInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetCustomerByInvoiceCompletedEventHandler(object sender, GetCustomerByInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerByInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerByInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Customer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Customer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getSoldProductsByDateCompletedEventHandler(object sender, getSoldProductsByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSoldProductsByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSoldProductsByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getSoldProductsByDatesCompletedEventHandler(object sender, getSoldProductsByDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSoldProductsByDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSoldProductsByDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getSoldProductsByInvoiceNoCompletedEventHandler(object sender, getSoldProductsByInvoiceNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSoldProductsByInvoiceNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSoldProductsByInvoiceNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getProfitLossByDateCompletedEventHandler(object sender, getProfitLossByDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProfitLossByDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProfitLossByDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void getProfitLossByDatesCompletedEventHandler(object sender, getProfitLossByDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getProfitLossByDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getProfitLossByDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SalesToCustomerByIDCompletedEventHandler(object sender, SalesToCustomerByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SalesToCustomerByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SalesToCustomerByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SalesToCustomerByDatesCompletedEventHandler(object sender, SalesToCustomerByDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SalesToCustomerByDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SalesToCustomerByDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateSalesCompletedEventHandler(object sender, UpdateSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void UpdateSaleDetailCompletedEventHandler(object sender, UpdateSaleDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSaleDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSaleDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Server2Client Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Server2Client)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591